from ex0.creature_factory import CreatureFactory, FlameFactory, AquaFactory

print("Testing factory")
FlameFac = FlameFactory()
Flame = FlameFac.create_base()
print(f"{Flame.describe()}")
print(f"{Flame.attack()}")
Pyro = FlameFac.create_evolved()
print(f"{Pyro.describe()}")
print(f"{Pyro.attack()}")

print()
print("Testing factory")
AquaFac = AquaFactory()
Aqua = AquaFac.create_base()
print(f"{Aqua.describe()}")
print(f"{Aqua.attack()}")
Torra = AquaFac.create_evolved()
print(f"{Torra.describe()}")
print(f"{Torra.attack()}")

print()
print("Testing battle")
print(f"{Flame.describe()}")
print(" vs.")
print(f"{Aqua.describe()}")
print(" fight!")
print(f"{Flame.attack()}")
print(f"{Aqua.attack()}")